-- MySQL Script generated by MySQL Workbench
-- Sun Oct  4 15:29:30 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`registros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`registros` ;

CREATE TABLE IF NOT EXISTS `mydb`.`registros` (
  `Jogo` INT NOT NULL AUTO_INCREMENT,
  `Placar` INT NOT NULL,
  `MinTemp` INT NOT NULL,
  `MaxTemp` INT NOT NULL,
  `QuebraRecMin` INT NOT NULL,
  `QuebraRecMax` INT NOT NULL,
  `id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
